server:
  port: 8084
  
spring:
  application:
    name: order-service  
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: $1Welcome
  jpa:
    hibernate:
      ddl:
        auto: update 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka